### ISSUE TITLE
download checkpoints/*.ckpt

### ISSUE THREAD

**Issue by tvshow5727** [eth-ait/MultiPly#3]
checkpoint = sorted(glob.glob("checkpoints/*.ckpt"))[-1]
    testset = create_dataset(opt.dataset.test)
    print("checkpoint:", checkpoint)
    trainer.test(model, testset, ckpt_path=checkpoint)
    # trainer.test(model, testset, ckpt_path="checkpoints/epoch=5299-loss=0.02430165372788906.ckpt")
    
    

I couldn't find the link to download the model，epoch=5299-loss=0.02430165372788906.ckpt；
how can i download the author's  model？or train my model？

**Comment by atonalfreerider** [comment]
When I ran
`python train.py`

it generated a checkpoint in:
../MultiPly/code/outputs/Hi4D/taichi01/checkpoints

The `taichi` data is hard coded into the configs and the scripts, so you have to change it if you want to train your own model on your own data

**Comment by jzr99** [comment]
Hi,

Thank John for the answer. 
I also uploaded a pretrained model checkpoint for taichi01 sequence [here](https://drive.google.com/file/d/1fsN0kaZW7i7tWLm0E5ZaLhjKf_YlVgas/view?usp=sharing). You can download it and put it into `../MultiPly/code/outputs/Hi4D/taichi01/checkpoints` then ran `python test.py` to directly test it without training.
