### ISSUE TITLE
Running preprocessing_multiple_trace.py without openpose causes errors

### ISSUE THREAD

**Issue by atonalfreerider** [eth-ait/MultiPly#6]
Reproduce: run without a reference to openpose
run_preprocessing_multiply.sh

proposed fixes:
https://github.com/eth-ait/MultiPly/compare/main...atonalfreerider:MultiPly:no-openpose

**Comment by jzr99** [comment]
Hi, 

The name of the parameter may be confusing. As for the preprocessing stage, using openpose is optional, but it is mandatory to use Vitpose. In the latter case, the parameter `openpose_paths` will be pointed to the output dir of the Vitpose.
