### ISSUE TITLE
Enable multi GPU's causes errors

### ISSUE THREAD

**Issue by tweezlednutball** [eth-ait/MultiPly#8]
devices=-1, in train.py with a machine with 2 more more GPU's causes these errors:
RuntimeError: It looks like your LightningModule has parameters that were not used in producing the loss returned by training_step. If this is intentional, you must enable the detection of unused parameters in DDP, either by setting the string value `strategy='ddp_find_unused_parameters_true'` or by setting the flag in the strategy with `strategy=DDPStrategy(find_unused_parameters=True)`.

When I add the string value `strategy='ddp_find_unused_parameters_true':
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument mat2 in method wrapper_CUDA_bmm)

**Comment by jzr99** [comment]
Hi,

Currently, our method does not support multiple GPU training. Set `export CUDA_VISIBLE_DEVICES=0` to choose gpu id before training.
